### ISSUE TITLE
Git戦略について

### ISSUE THREAD

**Issue by yuichi-star-alchemist** [2024-autumn-hackathon/container#2]
Gitの運用方法の提案です

1.mainがデプロイ用、developが開発統合用
2.開発内容をfeature/{name}ブランチを作成してリモートにpush
3.developにプルリクエスト
4.詳細を書いて伝わりやすくしましょう
①実装内容
(テストを書いていないなら)②どのような動作確認をしたか？
③その他
5.基本ペアの方が動作することの確認を行ってマージを行う
6.プルリクのボリュームが大きくなり過ぎないように機能一つ毎に

**Comment by abyMaya** [comment]
お疲れ様です。すみません、こちらにご案内いただいてるのに気づかずに、
プルリク済ませてしまってました。
バックエンド側の初期設定初期化に関するものでしたので、
少しボリューム大き目かもしれなかったのですが、一括でアップしなければ
意味がないような気がいたしましたので。。。
以降、ご提案にそってプルリクいたしますね！
